// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MachineDescription.proto

package org.robocup_logistics.llsf_msgs;

public final class MachineDescriptionProtos {
  private MachineDescriptionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code llsf_msgs.LightColor}
   */
  public enum LightColor
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RED = 0;</code>
     */
    RED(0, 0),
    /**
     * <code>YELLOW = 1;</code>
     */
    YELLOW(1, 1),
    /**
     * <code>GREEN = 2;</code>
     */
    GREEN(2, 2),
    ;

    /**
     * <code>RED = 0;</code>
     */
    public static final int RED_VALUE = 0;
    /**
     * <code>YELLOW = 1;</code>
     */
    public static final int YELLOW_VALUE = 1;
    /**
     * <code>GREEN = 2;</code>
     */
    public static final int GREEN_VALUE = 2;


    public final int getNumber() { return value; }

    public static LightColor valueOf(int value) {
      switch (value) {
        case 0: return RED;
        case 1: return YELLOW;
        case 2: return GREEN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LightColor>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<LightColor>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LightColor>() {
            public LightColor findValueByNumber(int number) {
              return LightColor.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final LightColor[] VALUES = values();

    public static LightColor valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private LightColor(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:llsf_msgs.LightColor)
  }

  /**
   * Protobuf enum {@code llsf_msgs.LightState}
   */
  public enum LightState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OFF = 0;</code>
     */
    OFF(0, 0),
    /**
     * <code>ON = 1;</code>
     */
    ON(1, 1),
    /**
     * <code>BLINK = 2;</code>
     */
    BLINK(2, 2),
    ;

    /**
     * <code>OFF = 0;</code>
     */
    public static final int OFF_VALUE = 0;
    /**
     * <code>ON = 1;</code>
     */
    public static final int ON_VALUE = 1;
    /**
     * <code>BLINK = 2;</code>
     */
    public static final int BLINK_VALUE = 2;


    public final int getNumber() { return value; }

    public static LightState valueOf(int value) {
      switch (value) {
        case 0: return OFF;
        case 1: return ON;
        case 2: return BLINK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LightState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<LightState>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LightState>() {
            public LightState findValueByNumber(int number) {
              return LightState.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.getDescriptor().getEnumTypes().get(1);
    }

    private static final LightState[] VALUES = values();

    public static LightState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private LightState(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:llsf_msgs.LightState)
  }

  /**
   * Protobuf enum {@code llsf_msgs.SSOp}
   */
  public enum SSOp
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STORE = 1;</code>
     */
    STORE(0, 1),
    /**
     * <code>RETRIEVE = 2;</code>
     */
    RETRIEVE(1, 2),
    ;

    /**
     * <code>STORE = 1;</code>
     */
    public static final int STORE_VALUE = 1;
    /**
     * <code>RETRIEVE = 2;</code>
     */
    public static final int RETRIEVE_VALUE = 2;


    public final int getNumber() { return value; }

    public static SSOp valueOf(int value) {
      switch (value) {
        case 1: return STORE;
        case 2: return RETRIEVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SSOp>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SSOp>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SSOp>() {
            public SSOp findValueByNumber(int number) {
              return SSOp.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.getDescriptor().getEnumTypes().get(2);
    }

    private static final SSOp[] VALUES = values();

    public static SSOp valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private SSOp(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:llsf_msgs.SSOp)
  }

  /**
   * Protobuf enum {@code llsf_msgs.CSOp}
   */
  public enum CSOp
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RETRIEVE_CAP = 1;</code>
     */
    RETRIEVE_CAP(0, 1),
    /**
     * <code>MOUNT_CAP = 2;</code>
     */
    MOUNT_CAP(1, 2),
    ;

    /**
     * <code>RETRIEVE_CAP = 1;</code>
     */
    public static final int RETRIEVE_CAP_VALUE = 1;
    /**
     * <code>MOUNT_CAP = 2;</code>
     */
    public static final int MOUNT_CAP_VALUE = 2;


    public final int getNumber() { return value; }

    public static CSOp valueOf(int value) {
      switch (value) {
        case 1: return RETRIEVE_CAP;
        case 2: return MOUNT_CAP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CSOp>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CSOp>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CSOp>() {
            public CSOp findValueByNumber(int number) {
              return CSOp.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.getDescriptor().getEnumTypes().get(3);
    }

    private static final CSOp[] VALUES = values();

    public static CSOp valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CSOp(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:llsf_msgs.CSOp)
  }

  public interface SSSlotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:llsf_msgs.SSSlot)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 x = 1;</code>
     *
     * <pre>
     * Ordering is a right hand coordinate system, starting at the left bottom front corner
     * </pre>
     */
    boolean hasX();
    /**
     * <code>required uint32 x = 1;</code>
     *
     * <pre>
     * Ordering is a right hand coordinate system, starting at the left bottom front corner
     * </pre>
     */
    int getX();

    /**
     * <code>required uint32 y = 2;</code>
     *
     * <pre>
     * [0-4] width;  the place on the shelf
     * </pre>
     */
    boolean hasY();
    /**
     * <code>required uint32 y = 2;</code>
     *
     * <pre>
     * [0-4] width;  the place on the shelf
     * </pre>
     */
    int getY();

    /**
     * <code>required uint32 z = 3;</code>
     *
     * <pre>
     * [0-1] depth;  the front or back row of the shelf
     * </pre>
     */
    boolean hasZ();
    /**
     * <code>required uint32 z = 3;</code>
     *
     * <pre>
     * [0-1] depth;  the front or back row of the shelf
     * </pre>
     */
    int getZ();
  }
  /**
   * Protobuf type {@code llsf_msgs.SSSlot}
   */
  public static final class SSSlot extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:llsf_msgs.SSSlot)
      SSSlotOrBuilder {
    // Use SSSlot.newBuilder() to construct.
    private SSSlot(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SSSlot(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SSSlot defaultInstance;
    public static SSSlot getDefaultInstance() {
      return defaultInstance;
    }

    public SSSlot getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SSSlot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              z_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.internal_static_llsf_msgs_SSSlot_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.internal_static_llsf_msgs_SSSlot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot.class, org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot.Builder.class);
    }

    public static com.google.protobuf.Parser<SSSlot> PARSER =
        new com.google.protobuf.AbstractParser<SSSlot>() {
      public SSSlot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SSSlot(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<SSSlot> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>required uint32 x = 1;</code>
     *
     * <pre>
     * Ordering is a right hand coordinate system, starting at the left bottom front corner
     * </pre>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 x = 1;</code>
     *
     * <pre>
     * Ordering is a right hand coordinate system, starting at the left bottom front corner
     * </pre>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>required uint32 y = 2;</code>
     *
     * <pre>
     * [0-4] width;  the place on the shelf
     * </pre>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 y = 2;</code>
     *
     * <pre>
     * [0-4] width;  the place on the shelf
     * </pre>
     */
    public int getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private int z_;
    /**
     * <code>required uint32 z = 3;</code>
     *
     * <pre>
     * [0-1] depth;  the front or back row of the shelf
     * </pre>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 z = 3;</code>
     *
     * <pre>
     * [0-1] depth;  the front or back row of the shelf
     * </pre>
     */
    public int getZ() {
      return z_;
    }

    private void initFields() {
      x_ = 0;
      y_ = 0;
      z_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, z_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code llsf_msgs.SSSlot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:llsf_msgs.SSSlot)
        org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.internal_static_llsf_msgs_SSSlot_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.internal_static_llsf_msgs_SSSlot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot.class, org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot.Builder.class);
      }

      // Construct using org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        z_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.internal_static_llsf_msgs_SSSlot_descriptor;
      }

      public org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot.getDefaultInstance();
      }

      public org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot build() {
        org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot buildPartial() {
        org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot result = new org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.z_ = z_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot other) {
        if (other == org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {

          return false;
        }
        if (!hasY()) {

          return false;
        }
        if (!hasZ()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robocup_logistics.llsf_msgs.MachineDescriptionProtos.SSSlot) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int x_ ;
      /**
       * <code>required uint32 x = 1;</code>
       *
       * <pre>
       * Ordering is a right hand coordinate system, starting at the left bottom front corner
       * </pre>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 x = 1;</code>
       *
       * <pre>
       * Ordering is a right hand coordinate system, starting at the left bottom front corner
       * </pre>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required uint32 x = 1;</code>
       *
       * <pre>
       * Ordering is a right hand coordinate system, starting at the left bottom front corner
       * </pre>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 x = 1;</code>
       *
       * <pre>
       * Ordering is a right hand coordinate system, starting at the left bottom front corner
       * </pre>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>required uint32 y = 2;</code>
       *
       * <pre>
       * [0-4] width;  the place on the shelf
       * </pre>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 y = 2;</code>
       *
       * <pre>
       * [0-4] width;  the place on the shelf
       * </pre>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>required uint32 y = 2;</code>
       *
       * <pre>
       * [0-4] width;  the place on the shelf
       * </pre>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 y = 2;</code>
       *
       * <pre>
       * [0-4] width;  the place on the shelf
       * </pre>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }

      private int z_ ;
      /**
       * <code>required uint32 z = 3;</code>
       *
       * <pre>
       * [0-1] depth;  the front or back row of the shelf
       * </pre>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 z = 3;</code>
       *
       * <pre>
       * [0-1] depth;  the front or back row of the shelf
       * </pre>
       */
      public int getZ() {
        return z_;
      }
      /**
       * <code>required uint32 z = 3;</code>
       *
       * <pre>
       * [0-1] depth;  the front or back row of the shelf
       * </pre>
       */
      public Builder setZ(int value) {
        bitField0_ |= 0x00000004;
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 z = 3;</code>
       *
       * <pre>
       * [0-1] depth;  the front or back row of the shelf
       * </pre>
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:llsf_msgs.SSSlot)
    }

    static {
      defaultInstance = new SSSlot(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:llsf_msgs.SSSlot)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_SSSlot_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_SSSlot_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030MachineDescription.proto\022\tllsf_msgs\")\n" +
      "\006SSSlot\022\t\n\001x\030\001 \002(\r\022\t\n\001y\030\002 \002(\r\022\t\n\001z\030\003 \002(\r" +
      "*,\n\nLightColor\022\007\n\003RED\020\000\022\n\n\006YELLOW\020\001\022\t\n\005G" +
      "REEN\020\002*(\n\nLightState\022\007\n\003OFF\020\000\022\006\n\002ON\020\001\022\t\n" +
      "\005BLINK\020\002*\037\n\004SSOp\022\t\n\005STORE\020\001\022\014\n\010RETRIEVE\020" +
      "\002*\'\n\004CSOp\022\020\n\014RETRIEVE_CAP\020\001\022\r\n\tMOUNT_CAP" +
      "\020\002B;\n\037org.robocup_logistics.llsf_msgsB\030M" +
      "achineDescriptionProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_llsf_msgs_SSSlot_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_llsf_msgs_SSSlot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_llsf_msgs_SSSlot_descriptor,
        new String[] { "X", "Y", "Z", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
