// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotMachineReport.proto

package org.robocup_logistics.llsf_msgs;

public final class RobotMachineReportProtos {
  private RobotMachineReportProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RobotMachineReportEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:llsf_msgs.RobotMachineReportEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     * Machine name and recognized type
     * and zone the machine is in
     * </pre>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     * Machine name and recognized type
     * and zone the machine is in
     * </pre>
     */
    String getName();
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     * Machine name and recognized type
     * and zone the machine is in
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .llsf_msgs.Zone zone = 3;</code>
     */
    boolean hasZone();
    /**
     * <code>optional .llsf_msgs.Zone zone = 3;</code>
     */
    org.robocup_logistics.llsf_msgs.ZoneProtos.Zone getZone();

    /**
     * <code>optional uint32 rotation = 4;</code>
     *
     * <pre>
     * [0-360] in deg
     * </pre>
     */
    boolean hasRotation();
    /**
     * <code>optional uint32 rotation = 4;</code>
     *
     * <pre>
     * [0-360] in deg
     * </pre>
     */
    int getRotation();

    /**
     * <code>optional string side = 5;</code>
     */
    boolean hasSide();
    /**
     * <code>optional string side = 5;</code>
     */
    String getSide();
    /**
     * <code>optional string side = 5;</code>
     */
    com.google.protobuf.ByteString
        getSideBytes();

    /**
     * <code>optional bool from_lidar = 6;</code>
     */
    boolean hasFromLidar();
    /**
     * <code>optional bool from_lidar = 6;</code>
     */
    boolean getFromLidar();
  }
  /**
   * Protobuf type {@code llsf_msgs.RobotMachineReportEntry}
   */
  public static final class RobotMachineReportEntry extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:llsf_msgs.RobotMachineReportEntry)
      RobotMachineReportEntryOrBuilder {
    // Use RobotMachineReportEntry.newBuilder() to construct.
    private RobotMachineReportEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RobotMachineReportEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RobotMachineReportEntry defaultInstance;
    public static RobotMachineReportEntry getDefaultInstance() {
      return defaultInstance;
    }

    public RobotMachineReportEntry getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RobotMachineReportEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              org.robocup_logistics.llsf_msgs.ZoneProtos.Zone value = org.robocup_logistics.llsf_msgs.ZoneProtos.Zone.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                zone_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              rotation_ = input.readUInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              side_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              fromLidar_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.internal_static_llsf_msgs_RobotMachineReportEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.internal_static_llsf_msgs_RobotMachineReportEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.class, org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.Builder.class);
    }

    public static com.google.protobuf.Parser<RobotMachineReportEntry> PARSER =
        new com.google.protobuf.AbstractParser<RobotMachineReportEntry>() {
      public RobotMachineReportEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RobotMachineReportEntry(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<RobotMachineReportEntry> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code llsf_msgs.RobotMachineReportEntry.CompType}
     */
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>COMP_ID = 2147;</code>
       */
      COMP_ID(0, 2147),
      /**
       * <code>MSG_TYPE = 1060;</code>
       */
      MSG_TYPE(1, 1060),
      ;

      /**
       * <code>COMP_ID = 2147;</code>
       */
      public static final int COMP_ID_VALUE = 2147;
      /**
       * <code>MSG_TYPE = 1060;</code>
       */
      public static final int MSG_TYPE_VALUE = 1060;


      public final int getNumber() { return value; }

      public static CompType valueOf(int value) {
        switch (value) {
          case 2147: return COMP_ID;
          case 1060: return MSG_TYPE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.getDescriptor().getEnumTypes().get(0);
      }

      private static final CompType[] VALUES = values();

      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:llsf_msgs.RobotMachineReportEntry.CompType)
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private Object name_;
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     * Machine name and recognized type
     * and zone the machine is in
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     * Machine name and recognized type
     * and zone the machine is in
     * </pre>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     *
     * <pre>
     * Machine name and recognized type
     * and zone the machine is in
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ZONE_FIELD_NUMBER = 3;
    private org.robocup_logistics.llsf_msgs.ZoneProtos.Zone zone_;
    /**
     * <code>optional .llsf_msgs.Zone zone = 3;</code>
     */
    public boolean hasZone() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .llsf_msgs.Zone zone = 3;</code>
     */
    public org.robocup_logistics.llsf_msgs.ZoneProtos.Zone getZone() {
      return zone_;
    }

    public static final int ROTATION_FIELD_NUMBER = 4;
    private int rotation_;
    /**
     * <code>optional uint32 rotation = 4;</code>
     *
     * <pre>
     * [0-360] in deg
     * </pre>
     */
    public boolean hasRotation() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 rotation = 4;</code>
     *
     * <pre>
     * [0-360] in deg
     * </pre>
     */
    public int getRotation() {
      return rotation_;
    }

    public static final int SIDE_FIELD_NUMBER = 5;
    private Object side_;
    /**
     * <code>optional string side = 5;</code>
     */
    public boolean hasSide() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string side = 5;</code>
     */
    public String getSide() {
      Object ref = side_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          side_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string side = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSideBytes() {
      Object ref = side_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        side_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROM_LIDAR_FIELD_NUMBER = 6;
    private boolean fromLidar_;
    /**
     * <code>optional bool from_lidar = 6;</code>
     */
    public boolean hasFromLidar() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool from_lidar = 6;</code>
     */
    public boolean getFromLidar() {
      return fromLidar_;
    }

    private void initFields() {
      name_ = "";
      zone_ = org.robocup_logistics.llsf_msgs.ZoneProtos.Zone.C_Z18;
      rotation_ = 0;
      side_ = "";
      fromLidar_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(3, zone_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(4, rotation_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getSideBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(6, fromLidar_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, zone_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, rotation_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSideBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, fromLidar_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code llsf_msgs.RobotMachineReportEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:llsf_msgs.RobotMachineReportEntry)
        org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.internal_static_llsf_msgs_RobotMachineReportEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.internal_static_llsf_msgs_RobotMachineReportEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.class, org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.Builder.class);
      }

      // Construct using org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        zone_ = org.robocup_logistics.llsf_msgs.ZoneProtos.Zone.C_Z18;
        bitField0_ = (bitField0_ & ~0x00000002);
        rotation_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        side_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        fromLidar_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.internal_static_llsf_msgs_RobotMachineReportEntry_descriptor;
      }

      public org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.getDefaultInstance();
      }

      public org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry build() {
        org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry buildPartial() {
        org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry result = new org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.zone_ = zone_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rotation_ = rotation_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.side_ = side_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fromLidar_ = fromLidar_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry other) {
        if (other == org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasZone()) {
          setZone(other.getZone());
        }
        if (other.hasRotation()) {
          setRotation(other.getRotation());
        }
        if (other.hasSide()) {
          bitField0_ |= 0x00000008;
          side_ = other.side_;
          onChanged();
        }
        if (other.hasFromLidar()) {
          setFromLidar(other.getFromLidar());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * Machine name and recognized type
       * and zone the machine is in
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * Machine name and recognized type
       * and zone the machine is in
       * </pre>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * Machine name and recognized type
       * and zone the machine is in
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * Machine name and recognized type
       * and zone the machine is in
       * </pre>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * Machine name and recognized type
       * and zone the machine is in
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       *
       * <pre>
       * Machine name and recognized type
       * and zone the machine is in
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private org.robocup_logistics.llsf_msgs.ZoneProtos.Zone zone_ = org.robocup_logistics.llsf_msgs.ZoneProtos.Zone.C_Z18;
      /**
       * <code>optional .llsf_msgs.Zone zone = 3;</code>
       */
      public boolean hasZone() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .llsf_msgs.Zone zone = 3;</code>
       */
      public org.robocup_logistics.llsf_msgs.ZoneProtos.Zone getZone() {
        return zone_;
      }
      /**
       * <code>optional .llsf_msgs.Zone zone = 3;</code>
       */
      public Builder setZone(org.robocup_logistics.llsf_msgs.ZoneProtos.Zone value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        zone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .llsf_msgs.Zone zone = 3;</code>
       */
      public Builder clearZone() {
        bitField0_ = (bitField0_ & ~0x00000002);
        zone_ = org.robocup_logistics.llsf_msgs.ZoneProtos.Zone.C_Z18;
        onChanged();
        return this;
      }

      private int rotation_ ;
      /**
       * <code>optional uint32 rotation = 4;</code>
       *
       * <pre>
       * [0-360] in deg
       * </pre>
       */
      public boolean hasRotation() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 rotation = 4;</code>
       *
       * <pre>
       * [0-360] in deg
       * </pre>
       */
      public int getRotation() {
        return rotation_;
      }
      /**
       * <code>optional uint32 rotation = 4;</code>
       *
       * <pre>
       * [0-360] in deg
       * </pre>
       */
      public Builder setRotation(int value) {
        bitField0_ |= 0x00000004;
        rotation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 rotation = 4;</code>
       *
       * <pre>
       * [0-360] in deg
       * </pre>
       */
      public Builder clearRotation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rotation_ = 0;
        onChanged();
        return this;
      }

      private Object side_ = "";
      /**
       * <code>optional string side = 5;</code>
       */
      public boolean hasSide() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string side = 5;</code>
       */
      public String getSide() {
        Object ref = side_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            side_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string side = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSideBytes() {
        Object ref = side_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          side_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string side = 5;</code>
       */
      public Builder setSide(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        side_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string side = 5;</code>
       */
      public Builder clearSide() {
        bitField0_ = (bitField0_ & ~0x00000008);
        side_ = getDefaultInstance().getSide();
        onChanged();
        return this;
      }
      /**
       * <code>optional string side = 5;</code>
       */
      public Builder setSideBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        side_ = value;
        onChanged();
        return this;
      }

      private boolean fromLidar_ ;
      /**
       * <code>optional bool from_lidar = 6;</code>
       */
      public boolean hasFromLidar() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool from_lidar = 6;</code>
       */
      public boolean getFromLidar() {
        return fromLidar_;
      }
      /**
       * <code>optional bool from_lidar = 6;</code>
       */
      public Builder setFromLidar(boolean value) {
        bitField0_ |= 0x00000010;
        fromLidar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool from_lidar = 6;</code>
       */
      public Builder clearFromLidar() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fromLidar_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:llsf_msgs.RobotMachineReportEntry)
    }

    static {
      defaultInstance = new RobotMachineReportEntry(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:llsf_msgs.RobotMachineReportEntry)
  }

  public interface RobotMachineReportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:llsf_msgs.RobotMachineReport)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .llsf_msgs.Team team_color = 2;</code>
     *
     * <pre>
     * Team for which the report is sent
     * </pre>
     */
    boolean hasTeamColor();
    /**
     * <code>required .llsf_msgs.Team team_color = 2;</code>
     *
     * <pre>
     * Team for which the report is sent
     * </pre>
     */
    org.robocup_logistics.llsf_msgs.TeamProtos.Team getTeamColor();

    /**
     * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
     *
     * <pre>
     * All machines already already recognized
     * or a subset thereof
     * </pre>
     */
    java.util.List<RobotMachineReportEntry>
        getMachinesList();
    /**
     * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
     *
     * <pre>
     * All machines already already recognized
     * or a subset thereof
     * </pre>
     */
    org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry getMachines(int index);
    /**
     * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
     *
     * <pre>
     * All machines already already recognized
     * or a subset thereof
     * </pre>
     */
    int getMachinesCount();
    /**
     * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
     *
     * <pre>
     * All machines already already recognized
     * or a subset thereof
     * </pre>
     */
    java.util.List<? extends RobotMachineReportEntryOrBuilder>
        getMachinesOrBuilderList();
    /**
     * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
     *
     * <pre>
     * All machines already already recognized
     * or a subset thereof
     * </pre>
     */
    org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntryOrBuilder getMachinesOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code llsf_msgs.RobotMachineReport}
   *
   * <pre>
   * Robots send this to announce recognized
   * machines to the refbox.
   * </pre>
   */
  public static final class RobotMachineReport extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:llsf_msgs.RobotMachineReport)
      RobotMachineReportOrBuilder {
    // Use RobotMachineReport.newBuilder() to construct.
    private RobotMachineReport(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RobotMachineReport(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RobotMachineReport defaultInstance;
    public static RobotMachineReport getDefaultInstance() {
      return defaultInstance;
    }

    public RobotMachineReport getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RobotMachineReport(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                machines_ = new java.util.ArrayList<RobotMachineReportEntry>();
                mutable_bitField0_ |= 0x00000002;
              }
              machines_.add(input.readMessage(org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.robocup_logistics.llsf_msgs.TeamProtos.Team value = org.robocup_logistics.llsf_msgs.TeamProtos.Team.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                teamColor_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          machines_ = java.util.Collections.unmodifiableList(machines_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.internal_static_llsf_msgs_RobotMachineReport_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.internal_static_llsf_msgs_RobotMachineReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport.class, org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport.Builder.class);
    }

    public static com.google.protobuf.Parser<RobotMachineReport> PARSER =
        new com.google.protobuf.AbstractParser<RobotMachineReport>() {
      public RobotMachineReport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RobotMachineReport(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<RobotMachineReport> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code llsf_msgs.RobotMachineReport.CompType}
     */
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>COMP_ID = 2148;</code>
       */
      COMP_ID(0, 2148),
      /**
       * <code>MSG_TYPE = 1061;</code>
       */
      MSG_TYPE(1, 1061),
      ;

      /**
       * <code>COMP_ID = 2148;</code>
       */
      public static final int COMP_ID_VALUE = 2148;
      /**
       * <code>MSG_TYPE = 1061;</code>
       */
      public static final int MSG_TYPE_VALUE = 1061;


      public final int getNumber() { return value; }

      public static CompType valueOf(int value) {
        switch (value) {
          case 2148: return COMP_ID;
          case 1061: return MSG_TYPE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport.getDescriptor().getEnumTypes().get(0);
      }

      private static final CompType[] VALUES = values();

      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:llsf_msgs.RobotMachineReport.CompType)
    }

    private int bitField0_;
    public static final int TEAM_COLOR_FIELD_NUMBER = 2;
    private org.robocup_logistics.llsf_msgs.TeamProtos.Team teamColor_;
    /**
     * <code>required .llsf_msgs.Team team_color = 2;</code>
     *
     * <pre>
     * Team for which the report is sent
     * </pre>
     */
    public boolean hasTeamColor() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .llsf_msgs.Team team_color = 2;</code>
     *
     * <pre>
     * Team for which the report is sent
     * </pre>
     */
    public org.robocup_logistics.llsf_msgs.TeamProtos.Team getTeamColor() {
      return teamColor_;
    }

    public static final int MACHINES_FIELD_NUMBER = 1;
    private java.util.List<RobotMachineReportEntry> machines_;
    /**
     * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
     *
     * <pre>
     * All machines already already recognized
     * or a subset thereof
     * </pre>
     */
    public java.util.List<RobotMachineReportEntry> getMachinesList() {
      return machines_;
    }
    /**
     * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
     *
     * <pre>
     * All machines already already recognized
     * or a subset thereof
     * </pre>
     */
    public java.util.List<? extends RobotMachineReportEntryOrBuilder>
        getMachinesOrBuilderList() {
      return machines_;
    }
    /**
     * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
     *
     * <pre>
     * All machines already already recognized
     * or a subset thereof
     * </pre>
     */
    public int getMachinesCount() {
      return machines_.size();
    }
    /**
     * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
     *
     * <pre>
     * All machines already already recognized
     * or a subset thereof
     * </pre>
     */
    public org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry getMachines(int index) {
      return machines_.get(index);
    }
    /**
     * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
     *
     * <pre>
     * All machines already already recognized
     * or a subset thereof
     * </pre>
     */
    public org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntryOrBuilder getMachinesOrBuilder(
        int index) {
      return machines_.get(index);
    }

    private void initFields() {
      teamColor_ = org.robocup_logistics.llsf_msgs.TeamProtos.Team.CYAN;
      machines_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTeamColor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMachinesCount(); i++) {
        if (!getMachines(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < machines_.size(); i++) {
        output.writeMessage(1, machines_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(2, teamColor_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < machines_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, machines_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, teamColor_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code llsf_msgs.RobotMachineReport}
     *
     * <pre>
     * Robots send this to announce recognized
     * machines to the refbox.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:llsf_msgs.RobotMachineReport)
        org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.internal_static_llsf_msgs_RobotMachineReport_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.internal_static_llsf_msgs_RobotMachineReport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport.class, org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport.Builder.class);
      }

      // Construct using org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMachinesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        teamColor_ = org.robocup_logistics.llsf_msgs.TeamProtos.Team.CYAN;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (machinesBuilder_ == null) {
          machines_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          machinesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.internal_static_llsf_msgs_RobotMachineReport_descriptor;
      }

      public org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport.getDefaultInstance();
      }

      public org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport build() {
        org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport buildPartial() {
        org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport result = new org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.teamColor_ = teamColor_;
        if (machinesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            machines_ = java.util.Collections.unmodifiableList(machines_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.machines_ = machines_;
        } else {
          result.machines_ = machinesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport other) {
        if (other == org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport.getDefaultInstance()) return this;
        if (other.hasTeamColor()) {
          setTeamColor(other.getTeamColor());
        }
        if (machinesBuilder_ == null) {
          if (!other.machines_.isEmpty()) {
            if (machines_.isEmpty()) {
              machines_ = other.machines_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMachinesIsMutable();
              machines_.addAll(other.machines_);
            }
            onChanged();
          }
        } else {
          if (!other.machines_.isEmpty()) {
            if (machinesBuilder_.isEmpty()) {
              machinesBuilder_.dispose();
              machinesBuilder_ = null;
              machines_ = other.machines_;
              bitField0_ = (bitField0_ & ~0x00000002);
              machinesBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMachinesFieldBuilder() : null;
            } else {
              machinesBuilder_.addAllMessages(other.machines_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTeamColor()) {

          return false;
        }
        for (int i = 0; i < getMachinesCount(); i++) {
          if (!getMachines(i).isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReport) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.robocup_logistics.llsf_msgs.TeamProtos.Team teamColor_ = org.robocup_logistics.llsf_msgs.TeamProtos.Team.CYAN;
      /**
       * <code>required .llsf_msgs.Team team_color = 2;</code>
       *
       * <pre>
       * Team for which the report is sent
       * </pre>
       */
      public boolean hasTeamColor() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .llsf_msgs.Team team_color = 2;</code>
       *
       * <pre>
       * Team for which the report is sent
       * </pre>
       */
      public org.robocup_logistics.llsf_msgs.TeamProtos.Team getTeamColor() {
        return teamColor_;
      }
      /**
       * <code>required .llsf_msgs.Team team_color = 2;</code>
       *
       * <pre>
       * Team for which the report is sent
       * </pre>
       */
      public Builder setTeamColor(org.robocup_logistics.llsf_msgs.TeamProtos.Team value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        teamColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .llsf_msgs.Team team_color = 2;</code>
       *
       * <pre>
       * Team for which the report is sent
       * </pre>
       */
      public Builder clearTeamColor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        teamColor_ = org.robocup_logistics.llsf_msgs.TeamProtos.Team.CYAN;
        onChanged();
        return this;
      }

      private java.util.List<RobotMachineReportEntry> machines_ =
        java.util.Collections.emptyList();
      private void ensureMachinesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          machines_ = new java.util.ArrayList<RobotMachineReportEntry>(machines_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry, org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.Builder, org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntryOrBuilder> machinesBuilder_;

      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public java.util.List<RobotMachineReportEntry> getMachinesList() {
        if (machinesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(machines_);
        } else {
          return machinesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public int getMachinesCount() {
        if (machinesBuilder_ == null) {
          return machines_.size();
        } else {
          return machinesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry getMachines(int index) {
        if (machinesBuilder_ == null) {
          return machines_.get(index);
        } else {
          return machinesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public Builder setMachines(
          int index, org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry value) {
        if (machinesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMachinesIsMutable();
          machines_.set(index, value);
          onChanged();
        } else {
          machinesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public Builder setMachines(
          int index, org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.Builder builderForValue) {
        if (machinesBuilder_ == null) {
          ensureMachinesIsMutable();
          machines_.set(index, builderForValue.build());
          onChanged();
        } else {
          machinesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public Builder addMachines(org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry value) {
        if (machinesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMachinesIsMutable();
          machines_.add(value);
          onChanged();
        } else {
          machinesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public Builder addMachines(
          int index, org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry value) {
        if (machinesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMachinesIsMutable();
          machines_.add(index, value);
          onChanged();
        } else {
          machinesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public Builder addMachines(
          org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.Builder builderForValue) {
        if (machinesBuilder_ == null) {
          ensureMachinesIsMutable();
          machines_.add(builderForValue.build());
          onChanged();
        } else {
          machinesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public Builder addMachines(
          int index, org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.Builder builderForValue) {
        if (machinesBuilder_ == null) {
          ensureMachinesIsMutable();
          machines_.add(index, builderForValue.build());
          onChanged();
        } else {
          machinesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public Builder addAllMachines(
          Iterable<? extends RobotMachineReportEntry> values) {
        if (machinesBuilder_ == null) {
          ensureMachinesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, machines_);
          onChanged();
        } else {
          machinesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public Builder clearMachines() {
        if (machinesBuilder_ == null) {
          machines_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          machinesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public Builder removeMachines(int index) {
        if (machinesBuilder_ == null) {
          ensureMachinesIsMutable();
          machines_.remove(index);
          onChanged();
        } else {
          machinesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.Builder getMachinesBuilder(
          int index) {
        return getMachinesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntryOrBuilder getMachinesOrBuilder(
          int index) {
        if (machinesBuilder_ == null) {
          return machines_.get(index);  } else {
          return machinesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public java.util.List<? extends RobotMachineReportEntryOrBuilder>
           getMachinesOrBuilderList() {
        if (machinesBuilder_ != null) {
          return machinesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(machines_);
        }
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.Builder addMachinesBuilder() {
        return getMachinesFieldBuilder().addBuilder(
            org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.Builder addMachinesBuilder(
          int index) {
        return getMachinesFieldBuilder().addBuilder(
            index, org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .llsf_msgs.RobotMachineReportEntry machines = 1;</code>
       *
       * <pre>
       * All machines already already recognized
       * or a subset thereof
       * </pre>
       */
      public java.util.List<RobotMachineReportEntry.Builder>
           getMachinesBuilderList() {
        return getMachinesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry, org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.Builder, org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntryOrBuilder>
          getMachinesFieldBuilder() {
        if (machinesBuilder_ == null) {
          machinesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry, org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntry.Builder, org.robocup_logistics.llsf_msgs.RobotMachineReportProtos.RobotMachineReportEntryOrBuilder>(
                  machines_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          machines_ = null;
        }
        return machinesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:llsf_msgs.RobotMachineReport)
    }

    static {
      defaultInstance = new RobotMachineReport(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:llsf_msgs.RobotMachineReport)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_RobotMachineReportEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_RobotMachineReportEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_llsf_msgs_RobotMachineReport_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_llsf_msgs_RobotMachineReport_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030RobotMachineReport.proto\022\tllsf_msgs\032\nT" +
      "eam.proto\032\nZone.proto\"\243\001\n\027RobotMachineRe" +
      "portEntry\022\014\n\004name\030\001 \002(\t\022\035\n\004zone\030\003 \001(\0162\017." +
      "llsf_msgs.Zone\022\020\n\010rotation\030\004 \001(\r\022\014\n\004side" +
      "\030\005 \001(\t\022\022\n\nfrom_lidar\030\006 \001(\010\"\'\n\010CompType\022\014" +
      "\n\007COMP_ID\020\343\020\022\r\n\010MSG_TYPE\020\244\010\"\230\001\n\022RobotMac" +
      "hineReport\022#\n\nteam_color\030\002 \002(\0162\017.llsf_ms" +
      "gs.Team\0224\n\010machines\030\001 \003(\0132\".llsf_msgs.Ro" +
      "botMachineReportEntry\"\'\n\010CompType\022\014\n\007COM" +
      "P_ID\020\344\020\022\r\n\010MSG_TYPE\020\245\010B;\n\037org.robocup_lo",
      "gistics.llsf_msgsB\030RobotMachineReportPro" +
      "tos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.robocup_logistics.llsf_msgs.TeamProtos.getDescriptor(),
          org.robocup_logistics.llsf_msgs.ZoneProtos.getDescriptor(),
        }, assigner);
    internal_static_llsf_msgs_RobotMachineReportEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_llsf_msgs_RobotMachineReportEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_llsf_msgs_RobotMachineReportEntry_descriptor,
        new String[] { "Name", "Zone", "Rotation", "Side", "FromLidar", });
    internal_static_llsf_msgs_RobotMachineReport_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_llsf_msgs_RobotMachineReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_llsf_msgs_RobotMachineReport_descriptor,
        new String[] { "TeamColor", "Machines", });
    org.robocup_logistics.llsf_msgs.TeamProtos.getDescriptor();
    org.robocup_logistics.llsf_msgs.ZoneProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
