// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Zone.proto

package org.robocup_logistics.llsf_msgs;

public final class ZoneProtos {
  private ZoneProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code llsf_msgs.Zone}
   *
   * <pre>
   * Zone identifiers
   * </pre>
   */
  public enum Zone
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>C_Z18 = 18;</code>
     */
    C_Z18(0, 18),
    /**
     * <code>C_Z28 = 28;</code>
     */
    C_Z28(1, 28),
    /**
     * <code>C_Z38 = 38;</code>
     */
    C_Z38(2, 38),
    /**
     * <code>C_Z48 = 48;</code>
     */
    C_Z48(3, 48),
    /**
     * <code>C_Z58 = 58;</code>
     */
    C_Z58(4, 58),
    /**
     * <code>C_Z68 = 68;</code>
     */
    C_Z68(5, 68),
    /**
     * <code>C_Z78 = 78;</code>
     */
    C_Z78(6, 78),
    /**
     * <code>C_Z17 = 17;</code>
     */
    C_Z17(7, 17),
    /**
     * <code>C_Z27 = 27;</code>
     */
    C_Z27(8, 27),
    /**
     * <code>C_Z37 = 37;</code>
     */
    C_Z37(9, 37),
    /**
     * <code>C_Z47 = 47;</code>
     */
    C_Z47(10, 47),
    /**
     * <code>C_Z57 = 57;</code>
     */
    C_Z57(11, 57),
    /**
     * <code>C_Z67 = 67;</code>
     */
    C_Z67(12, 67),
    /**
     * <code>C_Z77 = 77;</code>
     */
    C_Z77(13, 77),
    /**
     * <code>C_Z16 = 16;</code>
     */
    C_Z16(14, 16),
    /**
     * <code>C_Z26 = 26;</code>
     */
    C_Z26(15, 26),
    /**
     * <code>C_Z36 = 36;</code>
     */
    C_Z36(16, 36),
    /**
     * <code>C_Z46 = 46;</code>
     */
    C_Z46(17, 46),
    /**
     * <code>C_Z56 = 56;</code>
     */
    C_Z56(18, 56),
    /**
     * <code>C_Z66 = 66;</code>
     */
    C_Z66(19, 66),
    /**
     * <code>C_Z76 = 76;</code>
     */
    C_Z76(20, 76),
    /**
     * <code>C_Z15 = 15;</code>
     */
    C_Z15(21, 15),
    /**
     * <code>C_Z25 = 25;</code>
     */
    C_Z25(22, 25),
    /**
     * <code>C_Z35 = 35;</code>
     */
    C_Z35(23, 35),
    /**
     * <code>C_Z45 = 45;</code>
     */
    C_Z45(24, 45),
    /**
     * <code>C_Z55 = 55;</code>
     */
    C_Z55(25, 55),
    /**
     * <code>C_Z65 = 65;</code>
     */
    C_Z65(26, 65),
    /**
     * <code>C_Z75 = 75;</code>
     */
    C_Z75(27, 75),
    /**
     * <code>C_Z14 = 14;</code>
     */
    C_Z14(28, 14),
    /**
     * <code>C_Z24 = 24;</code>
     */
    C_Z24(29, 24),
    /**
     * <code>C_Z34 = 34;</code>
     */
    C_Z34(30, 34),
    /**
     * <code>C_Z44 = 44;</code>
     */
    C_Z44(31, 44),
    /**
     * <code>C_Z54 = 54;</code>
     */
    C_Z54(32, 54),
    /**
     * <code>C_Z64 = 64;</code>
     */
    C_Z64(33, 64),
    /**
     * <code>C_Z74 = 74;</code>
     */
    C_Z74(34, 74),
    /**
     * <code>C_Z13 = 13;</code>
     */
    C_Z13(35, 13),
    /**
     * <code>C_Z23 = 23;</code>
     */
    C_Z23(36, 23),
    /**
     * <code>C_Z33 = 33;</code>
     */
    C_Z33(37, 33),
    /**
     * <code>C_Z43 = 43;</code>
     */
    C_Z43(38, 43),
    /**
     * <code>C_Z53 = 53;</code>
     */
    C_Z53(39, 53),
    /**
     * <code>C_Z63 = 63;</code>
     */
    C_Z63(40, 63),
    /**
     * <code>C_Z73 = 73;</code>
     */
    C_Z73(41, 73),
    /**
     * <code>C_Z12 = 12;</code>
     */
    C_Z12(42, 12),
    /**
     * <code>C_Z22 = 22;</code>
     */
    C_Z22(43, 22),
    /**
     * <code>C_Z32 = 32;</code>
     */
    C_Z32(44, 32),
    /**
     * <code>C_Z42 = 42;</code>
     */
    C_Z42(45, 42),
    /**
     * <code>C_Z52 = 52;</code>
     */
    C_Z52(46, 52),
    /**
     * <code>C_Z62 = 62;</code>
     */
    C_Z62(47, 62),
    /**
     * <code>C_Z72 = 72;</code>
     */
    C_Z72(48, 72),
    /**
     * <code>C_Z11 = 11;</code>
     */
    C_Z11(49, 11),
    /**
     * <code>C_Z21 = 21;</code>
     */
    C_Z21(50, 21),
    /**
     * <code>C_Z31 = 31;</code>
     */
    C_Z31(51, 31),
    /**
     * <code>C_Z41 = 41;</code>
     */
    C_Z41(52, 41),
    /**
     * <code>M_Z18 = 1018;</code>
     */
    M_Z18(53, 1018),
    /**
     * <code>M_Z28 = 1028;</code>
     */
    M_Z28(54, 1028),
    /**
     * <code>M_Z38 = 1038;</code>
     */
    M_Z38(55, 1038),
    /**
     * <code>M_Z48 = 1048;</code>
     */
    M_Z48(56, 1048),
    /**
     * <code>M_Z58 = 1058;</code>
     */
    M_Z58(57, 1058),
    /**
     * <code>M_Z68 = 1068;</code>
     */
    M_Z68(58, 1068),
    /**
     * <code>M_Z78 = 1078;</code>
     */
    M_Z78(59, 1078),
    /**
     * <code>M_Z17 = 1017;</code>
     */
    M_Z17(60, 1017),
    /**
     * <code>M_Z27 = 1027;</code>
     */
    M_Z27(61, 1027),
    /**
     * <code>M_Z37 = 1037;</code>
     */
    M_Z37(62, 1037),
    /**
     * <code>M_Z47 = 1047;</code>
     */
    M_Z47(63, 1047),
    /**
     * <code>M_Z57 = 1057;</code>
     */
    M_Z57(64, 1057),
    /**
     * <code>M_Z67 = 1067;</code>
     */
    M_Z67(65, 1067),
    /**
     * <code>M_Z77 = 1077;</code>
     */
    M_Z77(66, 1077),
    /**
     * <code>M_Z16 = 1016;</code>
     */
    M_Z16(67, 1016),
    /**
     * <code>M_Z26 = 1026;</code>
     */
    M_Z26(68, 1026),
    /**
     * <code>M_Z36 = 1036;</code>
     */
    M_Z36(69, 1036),
    /**
     * <code>M_Z46 = 1046;</code>
     */
    M_Z46(70, 1046),
    /**
     * <code>M_Z56 = 1056;</code>
     */
    M_Z56(71, 1056),
    /**
     * <code>M_Z66 = 1066;</code>
     */
    M_Z66(72, 1066),
    /**
     * <code>M_Z76 = 1076;</code>
     */
    M_Z76(73, 1076),
    /**
     * <code>M_Z15 = 1015;</code>
     */
    M_Z15(74, 1015),
    /**
     * <code>M_Z25 = 1025;</code>
     */
    M_Z25(75, 1025),
    /**
     * <code>M_Z35 = 1035;</code>
     */
    M_Z35(76, 1035),
    /**
     * <code>M_Z45 = 1045;</code>
     */
    M_Z45(77, 1045),
    /**
     * <code>M_Z55 = 1055;</code>
     */
    M_Z55(78, 1055),
    /**
     * <code>M_Z65 = 1065;</code>
     */
    M_Z65(79, 1065),
    /**
     * <code>M_Z75 = 1075;</code>
     */
    M_Z75(80, 1075),
    /**
     * <code>M_Z14 = 1014;</code>
     */
    M_Z14(81, 1014),
    /**
     * <code>M_Z24 = 1024;</code>
     */
    M_Z24(82, 1024),
    /**
     * <code>M_Z34 = 1034;</code>
     */
    M_Z34(83, 1034),
    /**
     * <code>M_Z44 = 1044;</code>
     */
    M_Z44(84, 1044),
    /**
     * <code>M_Z54 = 1054;</code>
     */
    M_Z54(85, 1054),
    /**
     * <code>M_Z64 = 1064;</code>
     */
    M_Z64(86, 1064),
    /**
     * <code>M_Z74 = 1074;</code>
     */
    M_Z74(87, 1074),
    /**
     * <code>M_Z13 = 1013;</code>
     */
    M_Z13(88, 1013),
    /**
     * <code>M_Z23 = 1023;</code>
     */
    M_Z23(89, 1023),
    /**
     * <code>M_Z33 = 1033;</code>
     */
    M_Z33(90, 1033),
    /**
     * <code>M_Z43 = 1043;</code>
     */
    M_Z43(91, 1043),
    /**
     * <code>M_Z53 = 1053;</code>
     */
    M_Z53(92, 1053),
    /**
     * <code>M_Z63 = 1063;</code>
     */
    M_Z63(93, 1063),
    /**
     * <code>M_Z73 = 1073;</code>
     */
    M_Z73(94, 1073),
    /**
     * <code>M_Z12 = 1012;</code>
     */
    M_Z12(95, 1012),
    /**
     * <code>M_Z22 = 1022;</code>
     */
    M_Z22(96, 1022),
    /**
     * <code>M_Z32 = 1032;</code>
     */
    M_Z32(97, 1032),
    /**
     * <code>M_Z42 = 1042;</code>
     */
    M_Z42(98, 1042),
    /**
     * <code>M_Z52 = 1052;</code>
     */
    M_Z52(99, 1052),
    /**
     * <code>M_Z62 = 1062;</code>
     */
    M_Z62(100, 1062),
    /**
     * <code>M_Z72 = 1072;</code>
     */
    M_Z72(101, 1072),
    /**
     * <code>M_Z11 = 1011;</code>
     */
    M_Z11(102, 1011),
    /**
     * <code>M_Z21 = 1021;</code>
     */
    M_Z21(103, 1021),
    /**
     * <code>M_Z31 = 1031;</code>
     */
    M_Z31(104, 1031),
    /**
     * <code>M_Z41 = 1041;</code>
     */
    M_Z41(105, 1041),
    ;

    /**
     * <code>C_Z18 = 18;</code>
     */
    public static final int C_Z18_VALUE = 18;
    /**
     * <code>C_Z28 = 28;</code>
     */
    public static final int C_Z28_VALUE = 28;
    /**
     * <code>C_Z38 = 38;</code>
     */
    public static final int C_Z38_VALUE = 38;
    /**
     * <code>C_Z48 = 48;</code>
     */
    public static final int C_Z48_VALUE = 48;
    /**
     * <code>C_Z58 = 58;</code>
     */
    public static final int C_Z58_VALUE = 58;
    /**
     * <code>C_Z68 = 68;</code>
     */
    public static final int C_Z68_VALUE = 68;
    /**
     * <code>C_Z78 = 78;</code>
     */
    public static final int C_Z78_VALUE = 78;
    /**
     * <code>C_Z17 = 17;</code>
     */
    public static final int C_Z17_VALUE = 17;
    /**
     * <code>C_Z27 = 27;</code>
     */
    public static final int C_Z27_VALUE = 27;
    /**
     * <code>C_Z37 = 37;</code>
     */
    public static final int C_Z37_VALUE = 37;
    /**
     * <code>C_Z47 = 47;</code>
     */
    public static final int C_Z47_VALUE = 47;
    /**
     * <code>C_Z57 = 57;</code>
     */
    public static final int C_Z57_VALUE = 57;
    /**
     * <code>C_Z67 = 67;</code>
     */
    public static final int C_Z67_VALUE = 67;
    /**
     * <code>C_Z77 = 77;</code>
     */
    public static final int C_Z77_VALUE = 77;
    /**
     * <code>C_Z16 = 16;</code>
     */
    public static final int C_Z16_VALUE = 16;
    /**
     * <code>C_Z26 = 26;</code>
     */
    public static final int C_Z26_VALUE = 26;
    /**
     * <code>C_Z36 = 36;</code>
     */
    public static final int C_Z36_VALUE = 36;
    /**
     * <code>C_Z46 = 46;</code>
     */
    public static final int C_Z46_VALUE = 46;
    /**
     * <code>C_Z56 = 56;</code>
     */
    public static final int C_Z56_VALUE = 56;
    /**
     * <code>C_Z66 = 66;</code>
     */
    public static final int C_Z66_VALUE = 66;
    /**
     * <code>C_Z76 = 76;</code>
     */
    public static final int C_Z76_VALUE = 76;
    /**
     * <code>C_Z15 = 15;</code>
     */
    public static final int C_Z15_VALUE = 15;
    /**
     * <code>C_Z25 = 25;</code>
     */
    public static final int C_Z25_VALUE = 25;
    /**
     * <code>C_Z35 = 35;</code>
     */
    public static final int C_Z35_VALUE = 35;
    /**
     * <code>C_Z45 = 45;</code>
     */
    public static final int C_Z45_VALUE = 45;
    /**
     * <code>C_Z55 = 55;</code>
     */
    public static final int C_Z55_VALUE = 55;
    /**
     * <code>C_Z65 = 65;</code>
     */
    public static final int C_Z65_VALUE = 65;
    /**
     * <code>C_Z75 = 75;</code>
     */
    public static final int C_Z75_VALUE = 75;
    /**
     * <code>C_Z14 = 14;</code>
     */
    public static final int C_Z14_VALUE = 14;
    /**
     * <code>C_Z24 = 24;</code>
     */
    public static final int C_Z24_VALUE = 24;
    /**
     * <code>C_Z34 = 34;</code>
     */
    public static final int C_Z34_VALUE = 34;
    /**
     * <code>C_Z44 = 44;</code>
     */
    public static final int C_Z44_VALUE = 44;
    /**
     * <code>C_Z54 = 54;</code>
     */
    public static final int C_Z54_VALUE = 54;
    /**
     * <code>C_Z64 = 64;</code>
     */
    public static final int C_Z64_VALUE = 64;
    /**
     * <code>C_Z74 = 74;</code>
     */
    public static final int C_Z74_VALUE = 74;
    /**
     * <code>C_Z13 = 13;</code>
     */
    public static final int C_Z13_VALUE = 13;
    /**
     * <code>C_Z23 = 23;</code>
     */
    public static final int C_Z23_VALUE = 23;
    /**
     * <code>C_Z33 = 33;</code>
     */
    public static final int C_Z33_VALUE = 33;
    /**
     * <code>C_Z43 = 43;</code>
     */
    public static final int C_Z43_VALUE = 43;
    /**
     * <code>C_Z53 = 53;</code>
     */
    public static final int C_Z53_VALUE = 53;
    /**
     * <code>C_Z63 = 63;</code>
     */
    public static final int C_Z63_VALUE = 63;
    /**
     * <code>C_Z73 = 73;</code>
     */
    public static final int C_Z73_VALUE = 73;
    /**
     * <code>C_Z12 = 12;</code>
     */
    public static final int C_Z12_VALUE = 12;
    /**
     * <code>C_Z22 = 22;</code>
     */
    public static final int C_Z22_VALUE = 22;
    /**
     * <code>C_Z32 = 32;</code>
     */
    public static final int C_Z32_VALUE = 32;
    /**
     * <code>C_Z42 = 42;</code>
     */
    public static final int C_Z42_VALUE = 42;
    /**
     * <code>C_Z52 = 52;</code>
     */
    public static final int C_Z52_VALUE = 52;
    /**
     * <code>C_Z62 = 62;</code>
     */
    public static final int C_Z62_VALUE = 62;
    /**
     * <code>C_Z72 = 72;</code>
     */
    public static final int C_Z72_VALUE = 72;
    /**
     * <code>C_Z11 = 11;</code>
     */
    public static final int C_Z11_VALUE = 11;
    /**
     * <code>C_Z21 = 21;</code>
     */
    public static final int C_Z21_VALUE = 21;
    /**
     * <code>C_Z31 = 31;</code>
     */
    public static final int C_Z31_VALUE = 31;
    /**
     * <code>C_Z41 = 41;</code>
     */
    public static final int C_Z41_VALUE = 41;
    /**
     * <code>M_Z18 = 1018;</code>
     */
    public static final int M_Z18_VALUE = 1018;
    /**
     * <code>M_Z28 = 1028;</code>
     */
    public static final int M_Z28_VALUE = 1028;
    /**
     * <code>M_Z38 = 1038;</code>
     */
    public static final int M_Z38_VALUE = 1038;
    /**
     * <code>M_Z48 = 1048;</code>
     */
    public static final int M_Z48_VALUE = 1048;
    /**
     * <code>M_Z58 = 1058;</code>
     */
    public static final int M_Z58_VALUE = 1058;
    /**
     * <code>M_Z68 = 1068;</code>
     */
    public static final int M_Z68_VALUE = 1068;
    /**
     * <code>M_Z78 = 1078;</code>
     */
    public static final int M_Z78_VALUE = 1078;
    /**
     * <code>M_Z17 = 1017;</code>
     */
    public static final int M_Z17_VALUE = 1017;
    /**
     * <code>M_Z27 = 1027;</code>
     */
    public static final int M_Z27_VALUE = 1027;
    /**
     * <code>M_Z37 = 1037;</code>
     */
    public static final int M_Z37_VALUE = 1037;
    /**
     * <code>M_Z47 = 1047;</code>
     */
    public static final int M_Z47_VALUE = 1047;
    /**
     * <code>M_Z57 = 1057;</code>
     */
    public static final int M_Z57_VALUE = 1057;
    /**
     * <code>M_Z67 = 1067;</code>
     */
    public static final int M_Z67_VALUE = 1067;
    /**
     * <code>M_Z77 = 1077;</code>
     */
    public static final int M_Z77_VALUE = 1077;
    /**
     * <code>M_Z16 = 1016;</code>
     */
    public static final int M_Z16_VALUE = 1016;
    /**
     * <code>M_Z26 = 1026;</code>
     */
    public static final int M_Z26_VALUE = 1026;
    /**
     * <code>M_Z36 = 1036;</code>
     */
    public static final int M_Z36_VALUE = 1036;
    /**
     * <code>M_Z46 = 1046;</code>
     */
    public static final int M_Z46_VALUE = 1046;
    /**
     * <code>M_Z56 = 1056;</code>
     */
    public static final int M_Z56_VALUE = 1056;
    /**
     * <code>M_Z66 = 1066;</code>
     */
    public static final int M_Z66_VALUE = 1066;
    /**
     * <code>M_Z76 = 1076;</code>
     */
    public static final int M_Z76_VALUE = 1076;
    /**
     * <code>M_Z15 = 1015;</code>
     */
    public static final int M_Z15_VALUE = 1015;
    /**
     * <code>M_Z25 = 1025;</code>
     */
    public static final int M_Z25_VALUE = 1025;
    /**
     * <code>M_Z35 = 1035;</code>
     */
    public static final int M_Z35_VALUE = 1035;
    /**
     * <code>M_Z45 = 1045;</code>
     */
    public static final int M_Z45_VALUE = 1045;
    /**
     * <code>M_Z55 = 1055;</code>
     */
    public static final int M_Z55_VALUE = 1055;
    /**
     * <code>M_Z65 = 1065;</code>
     */
    public static final int M_Z65_VALUE = 1065;
    /**
     * <code>M_Z75 = 1075;</code>
     */
    public static final int M_Z75_VALUE = 1075;
    /**
     * <code>M_Z14 = 1014;</code>
     */
    public static final int M_Z14_VALUE = 1014;
    /**
     * <code>M_Z24 = 1024;</code>
     */
    public static final int M_Z24_VALUE = 1024;
    /**
     * <code>M_Z34 = 1034;</code>
     */
    public static final int M_Z34_VALUE = 1034;
    /**
     * <code>M_Z44 = 1044;</code>
     */
    public static final int M_Z44_VALUE = 1044;
    /**
     * <code>M_Z54 = 1054;</code>
     */
    public static final int M_Z54_VALUE = 1054;
    /**
     * <code>M_Z64 = 1064;</code>
     */
    public static final int M_Z64_VALUE = 1064;
    /**
     * <code>M_Z74 = 1074;</code>
     */
    public static final int M_Z74_VALUE = 1074;
    /**
     * <code>M_Z13 = 1013;</code>
     */
    public static final int M_Z13_VALUE = 1013;
    /**
     * <code>M_Z23 = 1023;</code>
     */
    public static final int M_Z23_VALUE = 1023;
    /**
     * <code>M_Z33 = 1033;</code>
     */
    public static final int M_Z33_VALUE = 1033;
    /**
     * <code>M_Z43 = 1043;</code>
     */
    public static final int M_Z43_VALUE = 1043;
    /**
     * <code>M_Z53 = 1053;</code>
     */
    public static final int M_Z53_VALUE = 1053;
    /**
     * <code>M_Z63 = 1063;</code>
     */
    public static final int M_Z63_VALUE = 1063;
    /**
     * <code>M_Z73 = 1073;</code>
     */
    public static final int M_Z73_VALUE = 1073;
    /**
     * <code>M_Z12 = 1012;</code>
     */
    public static final int M_Z12_VALUE = 1012;
    /**
     * <code>M_Z22 = 1022;</code>
     */
    public static final int M_Z22_VALUE = 1022;
    /**
     * <code>M_Z32 = 1032;</code>
     */
    public static final int M_Z32_VALUE = 1032;
    /**
     * <code>M_Z42 = 1042;</code>
     */
    public static final int M_Z42_VALUE = 1042;
    /**
     * <code>M_Z52 = 1052;</code>
     */
    public static final int M_Z52_VALUE = 1052;
    /**
     * <code>M_Z62 = 1062;</code>
     */
    public static final int M_Z62_VALUE = 1062;
    /**
     * <code>M_Z72 = 1072;</code>
     */
    public static final int M_Z72_VALUE = 1072;
    /**
     * <code>M_Z11 = 1011;</code>
     */
    public static final int M_Z11_VALUE = 1011;
    /**
     * <code>M_Z21 = 1021;</code>
     */
    public static final int M_Z21_VALUE = 1021;
    /**
     * <code>M_Z31 = 1031;</code>
     */
    public static final int M_Z31_VALUE = 1031;
    /**
     * <code>M_Z41 = 1041;</code>
     */
    public static final int M_Z41_VALUE = 1041;


    public final int getNumber() { return value; }

    public static Zone valueOf(int value) {
      switch (value) {
        case 18: return C_Z18;
        case 28: return C_Z28;
        case 38: return C_Z38;
        case 48: return C_Z48;
        case 58: return C_Z58;
        case 68: return C_Z68;
        case 78: return C_Z78;
        case 17: return C_Z17;
        case 27: return C_Z27;
        case 37: return C_Z37;
        case 47: return C_Z47;
        case 57: return C_Z57;
        case 67: return C_Z67;
        case 77: return C_Z77;
        case 16: return C_Z16;
        case 26: return C_Z26;
        case 36: return C_Z36;
        case 46: return C_Z46;
        case 56: return C_Z56;
        case 66: return C_Z66;
        case 76: return C_Z76;
        case 15: return C_Z15;
        case 25: return C_Z25;
        case 35: return C_Z35;
        case 45: return C_Z45;
        case 55: return C_Z55;
        case 65: return C_Z65;
        case 75: return C_Z75;
        case 14: return C_Z14;
        case 24: return C_Z24;
        case 34: return C_Z34;
        case 44: return C_Z44;
        case 54: return C_Z54;
        case 64: return C_Z64;
        case 74: return C_Z74;
        case 13: return C_Z13;
        case 23: return C_Z23;
        case 33: return C_Z33;
        case 43: return C_Z43;
        case 53: return C_Z53;
        case 63: return C_Z63;
        case 73: return C_Z73;
        case 12: return C_Z12;
        case 22: return C_Z22;
        case 32: return C_Z32;
        case 42: return C_Z42;
        case 52: return C_Z52;
        case 62: return C_Z62;
        case 72: return C_Z72;
        case 11: return C_Z11;
        case 21: return C_Z21;
        case 31: return C_Z31;
        case 41: return C_Z41;
        case 1018: return M_Z18;
        case 1028: return M_Z28;
        case 1038: return M_Z38;
        case 1048: return M_Z48;
        case 1058: return M_Z58;
        case 1068: return M_Z68;
        case 1078: return M_Z78;
        case 1017: return M_Z17;
        case 1027: return M_Z27;
        case 1037: return M_Z37;
        case 1047: return M_Z47;
        case 1057: return M_Z57;
        case 1067: return M_Z67;
        case 1077: return M_Z77;
        case 1016: return M_Z16;
        case 1026: return M_Z26;
        case 1036: return M_Z36;
        case 1046: return M_Z46;
        case 1056: return M_Z56;
        case 1066: return M_Z66;
        case 1076: return M_Z76;
        case 1015: return M_Z15;
        case 1025: return M_Z25;
        case 1035: return M_Z35;
        case 1045: return M_Z45;
        case 1055: return M_Z55;
        case 1065: return M_Z65;
        case 1075: return M_Z75;
        case 1014: return M_Z14;
        case 1024: return M_Z24;
        case 1034: return M_Z34;
        case 1044: return M_Z44;
        case 1054: return M_Z54;
        case 1064: return M_Z64;
        case 1074: return M_Z74;
        case 1013: return M_Z13;
        case 1023: return M_Z23;
        case 1033: return M_Z33;
        case 1043: return M_Z43;
        case 1053: return M_Z53;
        case 1063: return M_Z63;
        case 1073: return M_Z73;
        case 1012: return M_Z12;
        case 1022: return M_Z22;
        case 1032: return M_Z32;
        case 1042: return M_Z42;
        case 1052: return M_Z52;
        case 1062: return M_Z62;
        case 1072: return M_Z72;
        case 1011: return M_Z11;
        case 1021: return M_Z21;
        case 1031: return M_Z31;
        case 1041: return M_Z41;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Zone>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Zone>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Zone>() {
            public Zone findValueByNumber(int number) {
              return Zone.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.ZoneProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final Zone[] VALUES = values();

    public static Zone valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Zone(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:llsf_msgs.Zone)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nZone.proto\022\tllsf_msgs*\311\t\n\004Zone\022\t\n\005C_Z1" +
      "8\020\022\022\t\n\005C_Z28\020\034\022\t\n\005C_Z38\020&\022\t\n\005C_Z48\0200\022\t\n\005" +
      "C_Z58\020:\022\t\n\005C_Z68\020D\022\t\n\005C_Z78\020N\022\t\n\005C_Z17\020\021" +
      "\022\t\n\005C_Z27\020\033\022\t\n\005C_Z37\020%\022\t\n\005C_Z47\020/\022\t\n\005C_Z" +
      "57\0209\022\t\n\005C_Z67\020C\022\t\n\005C_Z77\020M\022\t\n\005C_Z16\020\020\022\t\n" +
      "\005C_Z26\020\032\022\t\n\005C_Z36\020$\022\t\n\005C_Z46\020.\022\t\n\005C_Z56\020" +
      "8\022\t\n\005C_Z66\020B\022\t\n\005C_Z76\020L\022\t\n\005C_Z15\020\017\022\t\n\005C_" +
      "Z25\020\031\022\t\n\005C_Z35\020#\022\t\n\005C_Z45\020-\022\t\n\005C_Z55\0207\022\t" +
      "\n\005C_Z65\020A\022\t\n\005C_Z75\020K\022\t\n\005C_Z14\020\016\022\t\n\005C_Z24" +
      "\020\030\022\t\n\005C_Z34\020\"\022\t\n\005C_Z44\020,\022\t\n\005C_Z54\0206\022\t\n\005C",
      "_Z64\020@\022\t\n\005C_Z74\020J\022\t\n\005C_Z13\020\r\022\t\n\005C_Z23\020\027\022" +
      "\t\n\005C_Z33\020!\022\t\n\005C_Z43\020+\022\t\n\005C_Z53\0205\022\t\n\005C_Z6" +
      "3\020?\022\t\n\005C_Z73\020I\022\t\n\005C_Z12\020\014\022\t\n\005C_Z22\020\026\022\t\n\005" +
      "C_Z32\020 \022\t\n\005C_Z42\020*\022\t\n\005C_Z52\0204\022\t\n\005C_Z62\020>" +
      "\022\t\n\005C_Z72\020H\022\t\n\005C_Z11\020\013\022\t\n\005C_Z21\020\025\022\t\n\005C_Z" +
      "31\020\037\022\t\n\005C_Z41\020)\022\n\n\005M_Z18\020\372\007\022\n\n\005M_Z28\020\204\010\022" +
      "\n\n\005M_Z38\020\216\010\022\n\n\005M_Z48\020\230\010\022\n\n\005M_Z58\020\242\010\022\n\n\005M" +
      "_Z68\020\254\010\022\n\n\005M_Z78\020\266\010\022\n\n\005M_Z17\020\371\007\022\n\n\005M_Z27" +
      "\020\203\010\022\n\n\005M_Z37\020\215\010\022\n\n\005M_Z47\020\227\010\022\n\n\005M_Z57\020\241\010\022" +
      "\n\n\005M_Z67\020\253\010\022\n\n\005M_Z77\020\265\010\022\n\n\005M_Z16\020\370\007\022\n\n\005M",
      "_Z26\020\202\010\022\n\n\005M_Z36\020\214\010\022\n\n\005M_Z46\020\226\010\022\n\n\005M_Z56" +
      "\020\240\010\022\n\n\005M_Z66\020\252\010\022\n\n\005M_Z76\020\264\010\022\n\n\005M_Z15\020\367\007\022" +
      "\n\n\005M_Z25\020\201\010\022\n\n\005M_Z35\020\213\010\022\n\n\005M_Z45\020\225\010\022\n\n\005M" +
      "_Z55\020\237\010\022\n\n\005M_Z65\020\251\010\022\n\n\005M_Z75\020\263\010\022\n\n\005M_Z14" +
      "\020\366\007\022\n\n\005M_Z24\020\200\010\022\n\n\005M_Z34\020\212\010\022\n\n\005M_Z44\020\224\010\022" +
      "\n\n\005M_Z54\020\236\010\022\n\n\005M_Z64\020\250\010\022\n\n\005M_Z74\020\262\010\022\n\n\005M" +
      "_Z13\020\365\007\022\n\n\005M_Z23\020\377\007\022\n\n\005M_Z33\020\211\010\022\n\n\005M_Z43" +
      "\020\223\010\022\n\n\005M_Z53\020\235\010\022\n\n\005M_Z63\020\247\010\022\n\n\005M_Z73\020\261\010\022" +
      "\n\n\005M_Z12\020\364\007\022\n\n\005M_Z22\020\376\007\022\n\n\005M_Z32\020\210\010\022\n\n\005M" +
      "_Z42\020\222\010\022\n\n\005M_Z52\020\234\010\022\n\n\005M_Z62\020\246\010\022\n\n\005M_Z72",
      "\020\260\010\022\n\n\005M_Z11\020\363\007\022\n\n\005M_Z21\020\375\007\022\n\n\005M_Z31\020\207\010\022" +
      "\n\n\005M_Z41\020\221\010B-\n\037org.robocup_logistics.lls" +
      "f_msgsB\nZoneProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
