// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MachineOrientationStateUpdate.proto

package org.robocup_logistics.llsf_msgs;

public final class MachineOrientationStateUpdateProtos {
  private MachineOrientationStateUpdateProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MachineOrientationStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:machineStates.MachineOrientationState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 robot_id = 1;</code>
     */
    boolean hasRobotId();
    /**
     * <code>required uint32 robot_id = 1;</code>
     */
    int getRobotId();

    /**
     * <code>optional bool found_machine = 2;</code>
     */
    boolean hasFoundMachine();
    /**
     * <code>optional bool found_machine = 2;</code>
     */
    boolean getFoundMachine();

    /**
     * <code>optional string machine_id = 3;</code>
     */
    boolean hasMachineId();
    /**
     * <code>optional string machine_id = 3;</code>
     */
    String getMachineId();
    /**
     * <code>optional string machine_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getMachineIdBytes();

    /**
     * <code>optional uint32 zone_number = 4;</code>
     */
    boolean hasZoneNumber();
    /**
     * <code>optional uint32 zone_number = 4;</code>
     */
    int getZoneNumber();

    /**
     * <code>optional string zone_prefix = 5;</code>
     */
    boolean hasZonePrefix();
    /**
     * <code>optional string zone_prefix = 5;</code>
     */
    String getZonePrefix();
    /**
     * <code>optional string zone_prefix = 5;</code>
     */
    com.google.protobuf.ByteString
        getZonePrefixBytes();

    /**
     * <code>optional double orientation = 6;</code>
     */
    boolean hasOrientation();
    /**
     * <code>optional double orientation = 6;</code>
     */
    double getOrientation();
  }
  /**
   * Protobuf type {@code machineStates.MachineOrientationState}
   *
   * <pre>
   * [START messages]
   * </pre>
   */
  public static final class MachineOrientationState extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:machineStates.MachineOrientationState)
      MachineOrientationStateOrBuilder {
    // Use MachineOrientationState.newBuilder() to construct.
    private MachineOrientationState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MachineOrientationState(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MachineOrientationState defaultInstance;
    public static MachineOrientationState getDefaultInstance() {
      return defaultInstance;
    }

    public MachineOrientationState getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MachineOrientationState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              robotId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              foundMachine_ = input.readBool();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              machineId_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              zoneNumber_ = input.readUInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              zonePrefix_ = bs;
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              orientation_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.internal_static_machineStates_MachineOrientationState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.internal_static_machineStates_MachineOrientationState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState.class, org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState.Builder.class);
    }

    public static com.google.protobuf.Parser<MachineOrientationState> PARSER =
        new com.google.protobuf.AbstractParser<MachineOrientationState>() {
      public MachineOrientationState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MachineOrientationState(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<MachineOrientationState> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code machineStates.MachineOrientationState.CompType}
     */
    public enum CompType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>COMP_ID = 6000;</code>
       */
      COMP_ID(0, 6000),
      /**
       * <code>MSG_TYPE = 201;</code>
       */
      MSG_TYPE(1, 201),
      ;

      /**
       * <code>COMP_ID = 6000;</code>
       */
      public static final int COMP_ID_VALUE = 6000;
      /**
       * <code>MSG_TYPE = 201;</code>
       */
      public static final int MSG_TYPE_VALUE = 201;


      public final int getNumber() { return value; }

      public static CompType valueOf(int value) {
        switch (value) {
          case 6000: return COMP_ID;
          case 201: return MSG_TYPE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CompType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CompType>() {
              public CompType findValueByNumber(int number) {
                return CompType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState.getDescriptor().getEnumTypes().get(0);
      }

      private static final CompType[] VALUES = values();

      public static CompType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CompType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:machineStates.MachineOrientationState.CompType)
    }

    private int bitField0_;
    public static final int ROBOT_ID_FIELD_NUMBER = 1;
    private int robotId_;
    /**
     * <code>required uint32 robot_id = 1;</code>
     */
    public boolean hasRobotId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 robot_id = 1;</code>
     */
    public int getRobotId() {
      return robotId_;
    }

    public static final int FOUND_MACHINE_FIELD_NUMBER = 2;
    private boolean foundMachine_;
    /**
     * <code>optional bool found_machine = 2;</code>
     */
    public boolean hasFoundMachine() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool found_machine = 2;</code>
     */
    public boolean getFoundMachine() {
      return foundMachine_;
    }

    public static final int MACHINE_ID_FIELD_NUMBER = 3;
    private Object machineId_;
    /**
     * <code>optional string machine_id = 3;</code>
     */
    public boolean hasMachineId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string machine_id = 3;</code>
     */
    public String getMachineId() {
      Object ref = machineId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          machineId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string machine_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMachineIdBytes() {
      Object ref = machineId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        machineId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ZONE_NUMBER_FIELD_NUMBER = 4;
    private int zoneNumber_;
    /**
     * <code>optional uint32 zone_number = 4;</code>
     */
    public boolean hasZoneNumber() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 zone_number = 4;</code>
     */
    public int getZoneNumber() {
      return zoneNumber_;
    }

    public static final int ZONE_PREFIX_FIELD_NUMBER = 5;
    private Object zonePrefix_;
    /**
     * <code>optional string zone_prefix = 5;</code>
     */
    public boolean hasZonePrefix() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string zone_prefix = 5;</code>
     */
    public String getZonePrefix() {
      Object ref = zonePrefix_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          zonePrefix_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string zone_prefix = 5;</code>
     */
    public com.google.protobuf.ByteString
        getZonePrefixBytes() {
      Object ref = zonePrefix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        zonePrefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIENTATION_FIELD_NUMBER = 6;
    private double orientation_;
    /**
     * <code>optional double orientation = 6;</code>
     */
    public boolean hasOrientation() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double orientation = 6;</code>
     */
    public double getOrientation() {
      return orientation_;
    }

    private void initFields() {
      robotId_ = 0;
      foundMachine_ = false;
      machineId_ = "";
      zoneNumber_ = 0;
      zonePrefix_ = "";
      orientation_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRobotId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, robotId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, foundMachine_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMachineIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, zoneNumber_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getZonePrefixBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, orientation_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, robotId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, foundMachine_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMachineIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, zoneNumber_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getZonePrefixBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, orientation_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code machineStates.MachineOrientationState}
     *
     * <pre>
     * [START messages]
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:machineStates.MachineOrientationState)
        org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.internal_static_machineStates_MachineOrientationState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.internal_static_machineStates_MachineOrientationState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState.class, org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState.Builder.class);
      }

      // Construct using org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        robotId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        foundMachine_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        machineId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        zoneNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        zonePrefix_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        orientation_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.internal_static_machineStates_MachineOrientationState_descriptor;
      }

      public org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState getDefaultInstanceForType() {
        return org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState.getDefaultInstance();
      }

      public org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState build() {
        org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState buildPartial() {
        org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState result = new org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.robotId_ = robotId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.foundMachine_ = foundMachine_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.machineId_ = machineId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.zoneNumber_ = zoneNumber_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.zonePrefix_ = zonePrefix_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.orientation_ = orientation_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState) {
          return mergeFrom((org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState other) {
        if (other == org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState.getDefaultInstance()) return this;
        if (other.hasRobotId()) {
          setRobotId(other.getRobotId());
        }
        if (other.hasFoundMachine()) {
          setFoundMachine(other.getFoundMachine());
        }
        if (other.hasMachineId()) {
          bitField0_ |= 0x00000004;
          machineId_ = other.machineId_;
          onChanged();
        }
        if (other.hasZoneNumber()) {
          setZoneNumber(other.getZoneNumber());
        }
        if (other.hasZonePrefix()) {
          bitField0_ |= 0x00000010;
          zonePrefix_ = other.zonePrefix_;
          onChanged();
        }
        if (other.hasOrientation()) {
          setOrientation(other.getOrientation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRobotId()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.robocup_logistics.llsf_msgs.MachineOrientationStateUpdateProtos.MachineOrientationState) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int robotId_ ;
      /**
       * <code>required uint32 robot_id = 1;</code>
       */
      public boolean hasRobotId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 robot_id = 1;</code>
       */
      public int getRobotId() {
        return robotId_;
      }
      /**
       * <code>required uint32 robot_id = 1;</code>
       */
      public Builder setRobotId(int value) {
        bitField0_ |= 0x00000001;
        robotId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 robot_id = 1;</code>
       */
      public Builder clearRobotId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        robotId_ = 0;
        onChanged();
        return this;
      }

      private boolean foundMachine_ ;
      /**
       * <code>optional bool found_machine = 2;</code>
       */
      public boolean hasFoundMachine() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool found_machine = 2;</code>
       */
      public boolean getFoundMachine() {
        return foundMachine_;
      }
      /**
       * <code>optional bool found_machine = 2;</code>
       */
      public Builder setFoundMachine(boolean value) {
        bitField0_ |= 0x00000002;
        foundMachine_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool found_machine = 2;</code>
       */
      public Builder clearFoundMachine() {
        bitField0_ = (bitField0_ & ~0x00000002);
        foundMachine_ = false;
        onChanged();
        return this;
      }

      private Object machineId_ = "";
      /**
       * <code>optional string machine_id = 3;</code>
       */
      public boolean hasMachineId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string machine_id = 3;</code>
       */
      public String getMachineId() {
        Object ref = machineId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            machineId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string machine_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMachineIdBytes() {
        Object ref = machineId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          machineId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string machine_id = 3;</code>
       */
      public Builder setMachineId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        machineId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string machine_id = 3;</code>
       */
      public Builder clearMachineId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        machineId_ = getDefaultInstance().getMachineId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string machine_id = 3;</code>
       */
      public Builder setMachineIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        machineId_ = value;
        onChanged();
        return this;
      }

      private int zoneNumber_ ;
      /**
       * <code>optional uint32 zone_number = 4;</code>
       */
      public boolean hasZoneNumber() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 zone_number = 4;</code>
       */
      public int getZoneNumber() {
        return zoneNumber_;
      }
      /**
       * <code>optional uint32 zone_number = 4;</code>
       */
      public Builder setZoneNumber(int value) {
        bitField0_ |= 0x00000008;
        zoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 zone_number = 4;</code>
       */
      public Builder clearZoneNumber() {
        bitField0_ = (bitField0_ & ~0x00000008);
        zoneNumber_ = 0;
        onChanged();
        return this;
      }

      private Object zonePrefix_ = "";
      /**
       * <code>optional string zone_prefix = 5;</code>
       */
      public boolean hasZonePrefix() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string zone_prefix = 5;</code>
       */
      public String getZonePrefix() {
        Object ref = zonePrefix_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            zonePrefix_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string zone_prefix = 5;</code>
       */
      public com.google.protobuf.ByteString
          getZonePrefixBytes() {
        Object ref = zonePrefix_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          zonePrefix_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string zone_prefix = 5;</code>
       */
      public Builder setZonePrefix(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        zonePrefix_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string zone_prefix = 5;</code>
       */
      public Builder clearZonePrefix() {
        bitField0_ = (bitField0_ & ~0x00000010);
        zonePrefix_ = getDefaultInstance().getZonePrefix();
        onChanged();
        return this;
      }
      /**
       * <code>optional string zone_prefix = 5;</code>
       */
      public Builder setZonePrefixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        zonePrefix_ = value;
        onChanged();
        return this;
      }

      private double orientation_ ;
      /**
       * <code>optional double orientation = 6;</code>
       */
      public boolean hasOrientation() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double orientation = 6;</code>
       */
      public double getOrientation() {
        return orientation_;
      }
      /**
       * <code>optional double orientation = 6;</code>
       */
      public Builder setOrientation(double value) {
        bitField0_ |= 0x00000020;
        orientation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double orientation = 6;</code>
       */
      public Builder clearOrientation() {
        bitField0_ = (bitField0_ & ~0x00000020);
        orientation_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:machineStates.MachineOrientationState)
    }

    static {
      defaultInstance = new MachineOrientationState(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:machineStates.MachineOrientationState)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_machineStates_MachineOrientationState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_machineStates_MachineOrientationState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n#MachineOrientationStateUpdate.proto\022\rm" +
      "achineStates\"\276\001\n\027MachineOrientationState" +
      "\022\020\n\010robot_id\030\001 \002(\r\022\025\n\rfound_machine\030\002 \001(" +
      "\010\022\022\n\nmachine_id\030\003 \001(\t\022\023\n\013zone_number\030\004 \001" +
      "(\r\022\023\n\013zone_prefix\030\005 \001(\t\022\023\n\013orientation\030\006" +
      " \001(\001\"\'\n\010CompType\022\014\n\007COMP_ID\020\360.\022\r\n\010MSG_TY" +
      "PE\020\311\001BF\n\037org.robocup_logistics.llsf_msgs" +
      "B#MachineOrientationStateUpdateProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_machineStates_MachineOrientationState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_machineStates_MachineOrientationState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_machineStates_MachineOrientationState_descriptor,
        new String[] { "RobotId", "FoundMachine", "MachineId", "ZoneNumber", "ZonePrefix", "Orientation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
